CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    avatar_image VARCHAR(500),
    bio VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE user_avatars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    image_data BYTEA NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE castaway (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    json_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    date_of_birth VARCHAR(255) NOT NULL,
    date_of_death VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    gender VARCHAR(255) NOT NULL,
    occupation VARCHAR(255) NOT NULL,
    hobbies VARCHAR(1000),
    pet_peeves VARCHAR(1000),
    three_words VARCHAR(255)
);

CREATE TABLE season (
    season INTEGER PRIMARY KEY,
    version VARCHAR(255) NOT NULL,
    season_name VARCHAR(500),
    location VARCHAR(500),
    country VARCHAR(255),
    tribe_setup VARCHAR(1000),
    full_name VARCHAR(500),
    filming_started VARCHAR(50),
    filming_ended VARCHAR(50),
    premiere_date VARCHAR(50),
    ending_date VARCHAR(50),
    viewers INTEGER,
    episodes_number INTEGER,
    game_data_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE episode (
    id INTEGER PRIMARY KEY,
    season_id INTEGER NOT NULL,
    episode_number INTEGER NOT NULL,
    episode_title VARCHAR(500) NOT NULL,
    episode_date VARCHAR(255) NOT NULL,
    episode_length INTEGER NOT NULL,
    is_finale BOOLEAN NOT NULL,
    episode_summary TEXT
);

CREATE TABLE castaway_performance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id INTEGER NOT NULL,
    castaway_id INTEGER NOT NULL
);

CREATE TABLE tribe (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL
);

CREATE TABLE groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    admin_id INTEGER NOT NULL,
    season_id INTEGER NOT NULL,
    draft_id INTEGER,
    latest_episode_watched_id INTEGER,
    first_scoring_episode_number INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    rule_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE group_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    joined_at TIMESTAMP NOT NULL,
    last_accessed_at TIMESTAMP,
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id)
);

CREATE TABLE teams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    team_name VARCHAR(100) NOT NULL,
    total_points INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_teams_group_user UNIQUE (group_id, user_id)
);

CREATE TABLE team_avatars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INTEGER NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    image_data BYTEA NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE drafts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    season_id INTEGER NOT NULL,
    created_by_user_id INTEGER,
    status VARCHAR(30) NOT NULL,
    style VARCHAR(30) NOT NULL,
    scheduled_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    team_size INTEGER NOT NULL,
    total_participants INTEGER NOT NULL,
    total_castaways INTEGER NOT NULL,
    max_drafts_per_castaway INTEGER NOT NULL,
    total_picks INTEGER NOT NULL,
    current_pick_number INTEGER NOT NULL,
    current_turn_user_id INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE draft_participants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    team_id INTEGER,
    draft_position INTEGER NOT NULL,
    picks_made INTEGER NOT NULL,
    max_drafts_per_castaway INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_draft_participants_draft_user UNIQUE (draft_id, user_id),
    CONSTRAINT uk_draft_participants_draft_position UNIQUE (draft_id, draft_position)
);

CREATE TABLE draft_picks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    castaway_performance_id INTEGER,
    pick_number INTEGER NOT NULL,
    round_number INTEGER NOT NULL,
    draft_position INTEGER NOT NULL,
    picked_at TIMESTAMP,
    CONSTRAINT uk_draft_picks_draft_pick_number UNIQUE (draft_id, pick_number),
    CONSTRAINT uk_draft_picks_draft_team_castaway UNIQUE (draft_id, team_id, castaway_performance_id)
);

CREATE TABLE draft_castaways (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id INTEGER NOT NULL,
    castaway_performance_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_draft_castaways_draft_castaway UNIQUE (draft_id, castaway_performance_id)
);

CREATE TABLE user_favorite_castaways (
    user_id INTEGER NOT NULL,
    castaway_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, castaway_id)
);

CREATE TABLE point_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    rule_type VARCHAR(255) NOT NULL,
    points INTEGER NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_point_rules_group_rule_type UNIQUE (group_id, rule_type)
);

CREATE TABLE group_score_calculation_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    season_id INTEGER NOT NULL,
    latest_episode_number INTEGER,
    first_scoring_episode_number INTEGER,
    rule_version INTEGER NOT NULL,
    game_data_version INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    error_message VARCHAR(1000)
);

CREATE TABLE team_castaways (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INTEGER NOT NULL,
    castaway_performance_id INTEGER NOT NULL,
    draft_order INTEGER,
    points INTEGER NOT NULL DEFAULT 0,
    drafted_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_team_castaways_team_castaway UNIQUE (team_id, castaway_performance_id)
);

CREATE TABLE team_castaway_score_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    team_castaway_id INTEGER NOT NULL,
    castaway_performance_id INTEGER NOT NULL,
    point_rule_id INTEGER NOT NULL,
    rule_type VARCHAR(255) NOT NULL,
    source_type VARCHAR(255) NOT NULL,
    source_id INTEGER NOT NULL,
    episode_number INTEGER,
    event_label VARCHAR(255),
    count_value INTEGER NOT NULL DEFAULT 1,
    points_each INTEGER NOT NULL,
    multiplier INTEGER NOT NULL DEFAULT 1,
    total_points INTEGER NOT NULL,
    calculation_run_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE challenge (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id INTEGER,
    episode_id INTEGER NOT NULL,
    challenge_id INTEGER NOT NULL,
    challenge_number INTEGER NOT NULL,
    challenge_type VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    balance BOOLEAN,
    endurance BOOLEAN,
    puzzle BOOLEAN,
    precision BOOLEAN,
    water BOOLEAN
);

CREATE TABLE challenge_performance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id INTEGER NOT NULL,
    castaway_performance_id INTEGER NOT NULL,
    place INTEGER,
    sat_out BOOLEAN NOT NULL,
    won BOOLEAN NOT NULL,
    won_individual_immunity BOOLEAN,
    won_team_immunity BOOLEAN,
    won_individual_reward BOOLEAN,
    won_team_reward BOOLEAN
);

CREATE TABLE journey (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id INTEGER NOT NULL,
    castaway_performance_id INTEGER NOT NULL,
    reward VARCHAR(255),
    lost_vote BOOLEAN NOT NULL,
    chose_to_play BOOLEAN,
    event VARCHAR(255)
);

CREATE TABLE advantage_movement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    castaway_id INTEGER NOT NULL,
    played_for_id INTEGER,
    episode_id INTEGER NOT NULL,
    event VARCHAR(255) NOT NULL,
    advantage_type VARCHAR(255) NOT NULL,
    success VARCHAR(255),
    votes_nullified INTEGER
);

CREATE TABLE boot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id INTEGER NOT NULL,
    tribal_id INTEGER UNIQUE,
    castaway_performance_id INTEGER NOT NULL,
    boot_order INTEGER NOT NULL,
    event VARCHAR(255) NOT NULL
);

CREATE TABLE tribal (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id INTEGER NOT NULL,
    tribe_id INTEGER NOT NULL,
    boot_order INTEGER NOT NULL
);

CREATE TABLE tribe_mapping (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id INTEGER NOT NULL,
    episode_id INTEGER NOT NULL,
    castaway_performance_id INTEGER NOT NULL,
    tribe_id INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE jury_vote (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id INTEGER NOT NULL,
    castaway_id INTEGER NOT NULL,
    voted_for_id INTEGER NOT NULL
);

CREATE TABLE vote_round (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tribal_id INTEGER NOT NULL,
    is_tie BOOLEAN NOT NULL,
    vote_order INTEGER
);

CREATE TABLE vote (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_round_id INTEGER NOT NULL,
    castaway_id INTEGER NOT NULL,
    voted_for_id INTEGER NOT NULL,
    nullified BOOLEAN
);

ALTER TABLE user_avatars
    ADD CONSTRAINT fk_user_avatars_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE episode
    ADD CONSTRAINT fk_episode_season FOREIGN KEY (season_id) REFERENCES season (season);

ALTER TABLE castaway_performance
    ADD CONSTRAINT fk_castaway_performance_season FOREIGN KEY (season_id) REFERENCES season (season),
    ADD CONSTRAINT fk_castaway_performance_castaway FOREIGN KEY (castaway_id) REFERENCES castaway (id);

ALTER TABLE tribe
    ADD CONSTRAINT fk_tribe_season FOREIGN KEY (season_id) REFERENCES season (season);

ALTER TABLE groups
    ADD CONSTRAINT fk_groups_admin FOREIGN KEY (admin_id) REFERENCES users (id),
    ADD CONSTRAINT fk_groups_season FOREIGN KEY (season_id) REFERENCES season (season),
    ADD CONSTRAINT fk_groups_draft FOREIGN KEY (draft_id) REFERENCES drafts (id),
    ADD CONSTRAINT fk_groups_latest_episode_watched FOREIGN KEY (latest_episode_watched_id) REFERENCES episode (id);

ALTER TABLE group_members
    ADD CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id),
    ADD CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE teams
    ADD CONSTRAINT fk_teams_group FOREIGN KEY (group_id) REFERENCES groups (id),
    ADD CONSTRAINT fk_teams_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE team_avatars
    ADD CONSTRAINT fk_team_avatars_team FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE drafts
    ADD CONSTRAINT fk_drafts_group FOREIGN KEY (group_id) REFERENCES groups (id),
    ADD CONSTRAINT fk_drafts_season FOREIGN KEY (season_id) REFERENCES season (season),
    ADD CONSTRAINT fk_drafts_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_drafts_current_turn_user FOREIGN KEY (current_turn_user_id) REFERENCES users (id);

ALTER TABLE draft_participants
    ADD CONSTRAINT fk_draft_participants_draft FOREIGN KEY (draft_id) REFERENCES drafts (id),
    ADD CONSTRAINT fk_draft_participants_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_draft_participants_team FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE draft_picks
    ADD CONSTRAINT fk_draft_picks_draft FOREIGN KEY (draft_id) REFERENCES drafts (id),
    ADD CONSTRAINT fk_draft_picks_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_draft_picks_team FOREIGN KEY (team_id) REFERENCES teams (id),
    ADD CONSTRAINT fk_draft_picks_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id);

ALTER TABLE draft_castaways
    ADD CONSTRAINT fk_draft_castaways_draft FOREIGN KEY (draft_id) REFERENCES drafts (id),
    ADD CONSTRAINT fk_draft_castaways_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id);

ALTER TABLE user_favorite_castaways
    ADD CONSTRAINT fk_user_favorite_castaways_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_user_favorite_castaways_castaway FOREIGN KEY (castaway_id) REFERENCES castaway (id);

ALTER TABLE point_rules
    ADD CONSTRAINT fk_point_rules_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_score_calculation_runs
    ADD CONSTRAINT fk_group_score_calculation_runs_group FOREIGN KEY (group_id) REFERENCES groups (id),
    ADD CONSTRAINT fk_group_score_calculation_runs_season FOREIGN KEY (season_id) REFERENCES season (season);

ALTER TABLE team_castaways
    ADD CONSTRAINT fk_team_castaways_team FOREIGN KEY (team_id) REFERENCES teams (id),
    ADD CONSTRAINT fk_team_castaways_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id);

ALTER TABLE team_castaway_score_events
    ADD CONSTRAINT fk_team_castaway_score_events_group FOREIGN KEY (group_id) REFERENCES groups (id),
    ADD CONSTRAINT fk_team_castaway_score_events_team FOREIGN KEY (team_id) REFERENCES teams (id),
    ADD CONSTRAINT fk_team_castaway_score_events_team_castaway FOREIGN KEY (team_castaway_id) REFERENCES team_castaways (id),
    ADD CONSTRAINT fk_team_castaway_score_events_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id),
    ADD CONSTRAINT fk_team_castaway_score_events_point_rule FOREIGN KEY (point_rule_id) REFERENCES point_rules (id),
    ADD CONSTRAINT fk_team_castaway_score_events_calculation_run FOREIGN KEY (calculation_run_id) REFERENCES group_score_calculation_runs (id);

ALTER TABLE challenge
    ADD CONSTRAINT fk_challenge_season FOREIGN KEY (season_id) REFERENCES season (season),
    ADD CONSTRAINT fk_challenge_episode FOREIGN KEY (episode_id) REFERENCES episode (id);

ALTER TABLE challenge_performance
    ADD CONSTRAINT fk_challenge_performance_challenge FOREIGN KEY (challenge_id) REFERENCES challenge (id),
    ADD CONSTRAINT fk_challenge_performance_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id);

ALTER TABLE journey
    ADD CONSTRAINT fk_journey_episode FOREIGN KEY (episode_id) REFERENCES episode (id),
    ADD CONSTRAINT fk_journey_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id);

ALTER TABLE advantage_movement
    ADD CONSTRAINT fk_advantage_movement_castaway FOREIGN KEY (castaway_id) REFERENCES castaway_performance (id),
    ADD CONSTRAINT fk_advantage_movement_played_for FOREIGN KEY (played_for_id) REFERENCES castaway_performance (id),
    ADD CONSTRAINT fk_advantage_movement_episode FOREIGN KEY (episode_id) REFERENCES episode (id);

ALTER TABLE boot
    ADD CONSTRAINT fk_boot_episode FOREIGN KEY (episode_id) REFERENCES episode (id),
    ADD CONSTRAINT fk_boot_tribal FOREIGN KEY (tribal_id) REFERENCES tribal (id),
    ADD CONSTRAINT fk_boot_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id);

ALTER TABLE tribal
    ADD CONSTRAINT fk_tribal_episode FOREIGN KEY (episode_id) REFERENCES episode (id),
    ADD CONSTRAINT fk_tribal_tribe FOREIGN KEY (tribe_id) REFERENCES tribe (id);

ALTER TABLE tribe_mapping
    ADD CONSTRAINT fk_tribe_mapping_season FOREIGN KEY (season_id) REFERENCES season (season),
    ADD CONSTRAINT fk_tribe_mapping_episode FOREIGN KEY (episode_id) REFERENCES episode (id),
    ADD CONSTRAINT fk_tribe_mapping_castaway_performance FOREIGN KEY (castaway_performance_id) REFERENCES castaway_performance (id),
    ADD CONSTRAINT fk_tribe_mapping_tribe FOREIGN KEY (tribe_id) REFERENCES tribe (id);

ALTER TABLE jury_vote
    ADD CONSTRAINT fk_jury_vote_episode FOREIGN KEY (episode_id) REFERENCES episode (id),
    ADD CONSTRAINT fk_jury_vote_castaway FOREIGN KEY (castaway_id) REFERENCES castaway_performance (id),
    ADD CONSTRAINT fk_jury_vote_voted_for FOREIGN KEY (voted_for_id) REFERENCES castaway_performance (id);

ALTER TABLE vote_round
    ADD CONSTRAINT fk_vote_round_tribal FOREIGN KEY (tribal_id) REFERENCES tribal (id);

ALTER TABLE vote
    ADD CONSTRAINT fk_vote_vote_round FOREIGN KEY (vote_round_id) REFERENCES vote_round (id),
    ADD CONSTRAINT fk_vote_castaway FOREIGN KEY (castaway_id) REFERENCES castaway_performance (id),
    ADD CONSTRAINT fk_vote_voted_for FOREIGN KEY (voted_for_id) REFERENCES castaway_performance (id);

CREATE INDEX idx_drafts_group_id ON drafts (group_id);
CREATE INDEX idx_drafts_status ON drafts (status);
CREATE INDEX idx_drafts_current_turn_user_id ON drafts (current_turn_user_id);
CREATE INDEX idx_draft_participants_draft_id ON draft_participants (draft_id);
CREATE INDEX idx_draft_participants_user_id ON draft_participants (user_id);
CREATE INDEX idx_draft_participants_team_id ON draft_participants (team_id);
CREATE INDEX idx_draft_picks_draft_id ON draft_picks (draft_id);
CREATE INDEX idx_draft_picks_team_id ON draft_picks (team_id);
CREATE INDEX idx_draft_picks_user_id ON draft_picks (user_id);
CREATE INDEX idx_draft_picks_castaway_performance_id ON draft_picks (castaway_performance_id);
CREATE INDEX idx_draft_castaways_draft_id ON draft_castaways (draft_id);
CREATE INDEX idx_draft_castaways_castaway_performance_id ON draft_castaways (castaway_performance_id);