CREATE TABLE IF NOT EXISTS notifications (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id  INTEGER     NOT NULL,
    type          VARCHAR(32) NOT NULL,
    read          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL,
    group_id      INTEGER,
    actor_id      INTEGER,
    episode_id    INTEGER,
    invitation_id INTEGER,
    CONSTRAINT fk_notif_recipient FOREIGN KEY (recipient_id) REFERENCES users(id),
    CONSTRAINT fk_notif_group     FOREIGN KEY (group_id)     REFERENCES groups(id),
    CONSTRAINT fk_notif_actor     FOREIGN KEY (actor_id)     REFERENCES users(id),
    CONSTRAINT fk_notif_episode   FOREIGN KEY (episode_id)   REFERENCES episode(id)
);

CREATE INDEX IF NOT EXISTS idx_notif_recipient_read    ON notifications (recipient_id, read);
CREATE INDEX IF NOT EXISTS idx_notif_recipient_created ON notifications (recipient_id, created_at DESC);
